[phases.setup]
nixPkgs = ["nodejs_22", "python3", "nodePackages.node-gyp"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "NODE_ENV=production node dist/index.cjs"
